name: CI

on:
  push:
    branches: [ main, master ]
    tags: ['v*', 'V*', '*.*.*']
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci
      # build job installs dependencies and can run build tasks if needed
      # (no build script is defined in package.json currently)

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm test
      # Packaging and release are handled in the `package` job which runs only on tags

  package:
    # run only for tag pushes
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: test
    # Give the job explicit permissions required to create releases & upload packages
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

      - name: Package VSIX
        run: npm run package

      - name: Verify VSIX exists
        run: |
          echo "Listing workspace files"
          ls -la
          echo "Checking for .vsix files"
          shopt -s nullglob || true
          VSIX_FILES=( *.vsix )
          if [ ${#VSIX_FILES[@]} -eq 0 ]; then
            echo "ERROR: No .vsix files found after packaging. Make sure 'npm run package' writes a .vsix into the workspace root or update the workflow path." 
            exit 1
          fi
          echo "Found VSIX: ${VSIX_FILES[0]}"

      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: '*.vsix'

      - name: Publish VSIX as GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    # Run semantic-release on branch pushes so it can create tags/releases itself
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
